config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :columns
  resources :categories

  root to: "columns#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    if user.role? :admin
        can :manage, :all
    elsif user.persisted?
        # logged in users who aren't admins
        can :read, Column
        can :read, Category
    else
        # non-logged in users
        can :index, Column
        can :read, Category
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true

  end
end

app/models/categorizer.rb
class Categorizer < ActiveRecord::Base
  belongs_to :column
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizers, dependent: :destroy
  has_many :columns, through: :categorizers
end

app/models/column.rb
class Column < ActiveRecord::Base
  has_many :categorizers, dependent: :destroy
  has_many :categories, through: :categorizers

  belongs_to :primary_category, class_name: 'Category'


  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(auth)
    if user = User.find_by_email(auth.info.email)
      user.provider = auth.provider
      user.uid = auth.uid
      user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
    end
  end


  def role?(role_to_compare)
    self.role.to_s == role_to_compare.to_s
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  
  def create
    @category = Category.new(category_params)
    @category.save
    redirect_to(categories_path)
  end

  def edit
  end

  def update
    @category.update(category_params)
    redirect_to(categories_path)
  end

  def destroy
    @category.destroy
    redirect_to(categories_path)
  end


  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category_name, :is_primary, :color, :live)
    end
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  load_and_authorize_resource
  before_action :set_primary_categories, only: [:edit, :update]


  def index
    # if there is a primary category in the params hash then run this query to filter by the columns with that category.
    if params[:primary_category_id]
      @columns = Column.where(primary_category_id: params[:primary_category_id]).order(publication_timestamp: :desc)
    else
      @columns = Column.all.order(publication_timestamp: :desc)
    end

    render @columns, layout: false if request.xhr?
  end

  def update
    @column.update(column_params)
    redirect_to(columns_path)
  end

  private
    def column_params
      params.require(:column).permit(:primary_category_id, {category_ids: [] })
    end

    def set_primary_categories
      @primary_categories = Category.where(is_primary: true)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def google_oauth2
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in Through Google!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      flash.notice = "Problem creating account"
      redirect_to new_user_registration_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/views/categories/_category.html.erb
<li><%= category.category_name %></li>
<li><%= category.color %></li>
<li>Primary: <%= category.is_primary %></li>
<li>Live: <%= category.live %></li>
<%= link_to "Edit", edit_category_path(category) %>
<%= button_to "Delete category", category_path(category), 
method: :delete, data: { confirm: "Are you sure you want to delete this category?" }, :class => "delete_button" %>
<br><br>

app/views/categories/_form.html.erb
<%= category.label :category_name %>
<%= category.text_field :category_name %><br>
<%= category.label :color %>
<%= category.text_field :color %><br>
<%= category.label :is_primary %>
<%= category.check_box :is_primary %><br>
<%= category.label :live %>
<%= category.check_box :live %><br>

app/views/categories/edit.html.erb
<h1>Add/remove categories</h1>
<%= form_for @category do |category| %>
  <%= render partial: 'form', locals: { category: category } %>
  <%= category.submit 'Save changes' %>
<% end %>

app/views/categories/index.html.erb
<ul>
  <%= render @categories %>  
</ul>
<%= link_to 'Add new category', new_category_path %>

app/views/categories/new.html.erb
<h1>Add a new category</h1>
<%= form_for @category do |category| %>
  <%= render partial: 'form', locals: { category: category } %>
  <%= category.submit 'Create category' %>
<% end %>

app/views/categories/show.html.erb
<div class="lucypedia-page-header">
    <p id="indignant-origami-font-override-1">Lucy Kellaway on <%= @category.category_name.downcase %></p>   
</div>

<% Column.where(primary_category_id: @category.id).each do |column| %>
  <%= render :partial => "columns/column", locals: { column: column } %>
<% end %>

app/views/columns/_column.html.erb
<h3 class="dear-lucy-headline">
  <% if column.primary_category %>

    <span>
      <%= form_tag columns_path, method: :get, remote: true, class: "category-filter-form" do %>
          <%# send the category_name somehow %>
          <%= hidden_field_tag :primary_category_id, column.primary_category.id %>
          <%= submit_tag column.primary_category.try(:category_name), :class => "#{column.primary_category.try :color} primary-tag" %>
      <% end %>
    </span>

  <% end %>
  <%= column.headline %>
</h3>



<%= column.parsed_question.html_safe %>

<p class="column-question-footer">
  <a class="lucy-answer-button" data-text-swap="Hide answer" href="#">
    <i class="o-ft-icons-icon o-ft-icons-icon--arrow-right demo-icon">
    </i> Lucy's answer</a>
  <span class="publication-timestamp">
  <%= column.publication_timestamp.strftime("%b %-d, %Y") %>
  </span>
</p>

<div class="lucys-answer">
  <%= column.parsed_answer.html_safe %>
  <!-- <ol>
    <%# column.categorizers.each do |categorizer| %>
      <li><%#= categorizer.category.try(:category_name) %></li>
    <%# end %>
  </ol> -->

  <%= link_to 'View on FT.com', column.story_url %><br><br>
</div>

<% if can? :update, @column %>
<br><br>
  <%= link_to 'Edit column categories', edit_column_path(column) %>
<% end %>

app/views/columns/edit.html.erb
<h1>Add/remove categories</h1>
<%= form_for @column do |column| %>
  <%= column.label :primary_category_id, 'Primary category' %>
  <%= column.collection_select :primary_category_id, @primary_categories.order(category_name: :asc), :id, :category_name %>
  <br><br>
  <div class="checkbox-list">
    <%= column.collection_check_boxes :category_ids, Category.all.order(category_name: :asc), :id, :category_name, {:item_wrapper_class => 'checkbox_container'} %>
  </div>
  <br><br>
  <%= column.submit 'Save changes' %>
<% end %>
<br><br>


<h3><%= @column.headline %></h3>
<%= @column.parsed_question.html_safe %>
<p>Originally published on <%= @column.publication_timestamp.strftime("%b %-d, %Y") %></p>
<strong>END QUESTION</strong>
<%= @column.parsed_answer.html_safe %>

app/views/columns/index.html.erb
<div class="lucypedia-page-header">
    <p id="indignant-origami-font-override-1">Lucy Kellaway on...</p>   
</div>
<div class="columns-container">
  <%= render @columns %>
</div>

app/views/columns/show.html.erb
<h3><%= @column.headline %></h3>
<p>Primary category: 
  <%= @column.primary_category.try :category_name %>
</p>

<p>Other categories:
  <ol>
    <% @column.categorizers.each do |categorizer| %>
      <li><%= categorizer.category.try(:category_name) %></li>
    <% end %>
  </ol>
</p>
<% if can? :update, @column %>
<br><br>
  <%= link_to 'Edit column categories', edit_column_path(@column) %>
<% end %>
<br><br>
<%= @column.parsed_question.html_safe %>
<p>Originally published on <%= @column.publication_timestamp.strftime("%b %-d, %Y") %></p>
<strong>END QUESTION</strong>
<%= @column.parsed_answer.html_safe %>
<strong>END ANSWER</strong>

app/views/layouts/_nav.html.erb
<% if can? :manage, :all %>
  <div class="admin-panel-wrapper">
    <ul>
      <li>
        <%= link_to 'Dear Lucy Index', columns_path %>
      </li>
      <li>
        <%= link_to 'Manage categories', categories_path %>
      </li>
    </ul>
  </div>
<% end %>

<header data-o-component="o-ft-header" class="o-ft-header o-registry-demo-chunk">
  <div class="o-ft-header__container">
    <div class="o-ft-header__primary">
      <div class="o-ft-header__primary__left">
  <div class="o-ft-header__logo o-ft-header__logo--ft">
    <a href="http://www.ft.com"><abbr title="Financial Times">FT</abbr></a>
  </div>
              <h1 class="o-ft-header__ft-masthead">Lucypedia</h1>
</div>

<nav class="o-ft-header__primary__center o-hierarchical-nav o-ft-header__nav--primary-theme" data-o-component="o-hierarchical-nav" data-o-version="0.2.8">
  <ul data-o-hierarchical-nav-level="1">
    <li data-priority="3"><%= link_to 'Home', columns_path %></li>
    <li data-priority="3"><div class='login'>
      <% if current_user %>
        <%= current_user.email %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%#= link_to "Sign In", new_user_session_path %>
        <%#= link_to "Register", new_user_registration_path %>
        <%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %>
      <% end %>
    </div></li>
    <li data-more="" class="o-hierarchical-nav__parent" aria-hidden="true"><a><span class="o-hierarchical-nav__more--if-some">More <i class="o-hierarchical-nav__parent__down-arrow"></i></span><span class="o-hierarchical-nav__more--if-all">Menu <i class="o-hierarchical-nav__parent__down-arrow"></i></span></a></li>
  </ul>
</nav>
          
    </div>
    <div class="o-ft-header__secondary">
      <div class="o-ft-header__secondary__left">
  <h2 class="o-ft-header__tagline"></h2>
</div>
<div class="o-ft-header__secondary__right">
</div>

    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lucypedia</title>
  <%#= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <link rel="stylesheet" href="//build.origami.ft.com/bundles/css?modules=o-ft-header@^2.5.15,o-ft-footer@^2.0.4,o-ft-icons@^2.3.4">
</head>

<body>
  <%= render partial: "layouts/nav"  %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <div class="main-container-wrapper">
    <%= yield %>
  </div>

  <%= render partial: "layouts/footer" %>
  <script src="//build.origami.ft.com/bundles/js?modules=o-ft-header@^2.5.15,o-ft-footer@^2.0.4,o-ft-icons@^2.3.4"></script>
</body>
</html>